seml:
  executable: experiment021123.py
  name: val_run
  output_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction_save/transVAE_experiment_logs/logs_021123
  project_root_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction/transVAE_seml/

slurm:
  experiments_per_job: 2
  max_simultaneous_jobs: 25
  sbatch_options:
    nodes: 1
    ntasks-per-node: 1
    gpus-per-task: 1
    mem: 62G          
    cpus-per-task: 12
    time: 3-00:00
    partition: gpu
    exclude: gwn[01-08]

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  max_epochs: 1
  dataset_to_predict: wang_to_predict_3000hvg.h5ad
  dataset_ground_truth1: dbdb_ground_truth_3000hvg.h5ad
  dataset_ground_truth2: mSTZ_ground_truth_3000hvg.h5ad
  cov_embed_dims: 10
  kl_weight: 0.005
  save_folder_name: regularisation_validation_eval_021123
  save_models: True
  learning_rate: 0.0001
  n_latent: 512
  n_hidden: 1000
  n_layers: 10
  dropout_rate: 0.4
  weight_decay: 0.001
  seed: 42

grid:
  addl_dataset_train:
    type: choice
    options:
     - train_adata_baseline_3000hvg.h5ad
     - embedding_top30_mouse_3000hvg.h5ad
