seml:
  executable: Experiment_baseline_transVAE.py
  name: extra
  output_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction/transVAE_seml/logs
  project_root_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction/transVAE_seml/

slurm:
  experiments_per_job: 8
  max_simultaneous_jobs: 10
  sbatch_options:
    nodes: 1
    ntasks-per-node: 1
    gpus-per-task: 1
    mem: 32G          
    cpus-per-task: 12
    time: 3-00:00
    partition: gpu

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  max_epochs: 1000
  dataset_to_predict: Wang_to_predict_top3000_baseline_hvg.h5ad
  dataset_ground_truth1: dbdb_ground_truth_top3000_baseline_hvg.h5ad
  dataset_ground_truth2: mSTZ_ground_truth_top3000_baseline_hvg.h5ad
  cov_embed_dims: 10
  kl_weight: 0.005
  save_folder_name: extra_models_save
  save_models: False

grid:
  dataset_train: 
    type: choice
    options:
     - extra_mouse_chem.h5ad
     - extra_mouse_chem.h5ad
     - extra_mouse_Embryonic.h5ad
     - extra_mouse_T1D.h5ad
     - extra_mouse_young.h5ad

  learning_rate:
    type: choice
    options:
     - 0.001
     - 0.005

  n_hidden:
    type: range
    min: 800
    max: 1201
    step: 200
    
  n_layers:
    type: range
    min: 2
    max: 6
    step: 2
    
  dropout_rate:
    type: choice
    options:
     - 0.3

  n_latent:
    type: choice
    options:
     - 512
      
  seed:
    type: choice
    options:
     - 42
     - 43
     - 44