seml:
  executable: experiment211123.py
  name: random_gene_test
  output_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction_save/transVAE_experiment_logs/logs_211123
  project_root_dir: /d/hpc/projects/FRI/DL/mo6643/MSC/cross_species_prediction/transVAE_seml/

slurm:
  experiments_per_job: 2
  max_simultaneous_jobs: 30
  sbatch_options:
    nodes: 1
    ntasks-per-node: 1
    gpus-per-task: 1
    mem: 62G          
    cpus-per-task: 12
    time: 3-00:00
    partition: gpu
    exclude: gwn[01-08]

###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  max_epochs: 1500
  dataset_to_predict: wang_to_predict_cleanCT.h5ad
  dataset_ground_truth1: dbdb_ground_truth_cleanCT.h5ad
  dataset_ground_truth2: mSTZ_ground_truth_cleanCT.h5ad
  cov_embed_dims: 10
  kl_weight: 0.005
  save_folder_name: random_sample_datasets
  save_models: False
  learning_rate: 0.0001
  n_latent: 512
  n_hidden: 1000
  n_layers: 6
  dropout_rate: 0.0001
  weight_decay: 0.3

grid:
  addl_dataset_train:
    type: choice
    options:
     - train_adata_baseline.h5ad
     - embedding_top30_mouse.h5ad
     - extra_human_neonatal.h5ad
     - random_mouse_seed_42.h5ad
     - extra_human_chem.h5ad
     - embedding_top50_mouse.h5ad
     - embedding_top70_human.h5ad
     - extra_mouse_aged.h5ad
     - embedding_top50_human.h5ad
     - extra_mouse_T1D.h5ad
     - extra_mouse_Embryonic.h5ad
     - random_human_seed_43.h5ad
     - embedding_top70_mouse.h5ad
     - embedding_top100_mouse.h5ad
     - embedding_top30_human.h5ad
     - random_human_seed_42.h5ad
     - extra_human_preT2D.h5ad
     - extra_mouse_chem.h5ad
     - random_mouse_seed_43.h5ad
     - extra_mouse_young.h5ad
    
  seed:
    type: choice
    options:
     - 42
     - 43
     - 44
     
  seed_for_genes:
    type: choice
    options:
     - 40
     - 41
     - 42
     - 43
     - 44
     - 45
     - 46
     - 47
     - 48
     - 49